- name: Set timezone
  timezone: name="{{ timezone }}"

- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  changed_when: False

- name: Correct interfaces
  template: src=network-interfaces dest=/etc/network/interfaces

- name: Add useDns=no to /etc/ssh/sshd_config
  lineinfile: dest=/etc/ssh/sshd_config state=present line="UseDNS no" insertafter="EOF"

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }}\t{{item}}" state=present backup=yes
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['nodes'] }}"

- name: set-up vagrant ssh keys
  copy: src='{{ lookup('env','HOME') }}/.vagrant.d/insecure_private_key' dest=/home/vagrant/.ssh/id_rsa mode=0600 owner=vagrant group=vagrant

- name: set-up vagrant id_rsa_pub
  copy: src=/home/vagrant/.ssh/authorized_keys dest=/home/vagrant/.ssh/id_rsa.pub remote_src=yes mode=0600 owner=vagrant group=vagrant

- name: set-up .ssh/config
  template: src=ssh-config.j2 dest=/home/vagrant/.ssh/config mode=0600 owner=vagrant group=vagrant
